### ISSUE TITLE
[5pt] create tool for bandit aggregate

### ISSUE THREAD

**Issue by goern** [thoth-station/si-aggregator#1]
As an Argo Workflow,
I want to call a command-line tool,
so that it calculates an aggregated SI score from SI bandit
and so that it outputs the report as JSON

Story-Points: 5

**Acceptance Criteria**
* tool reads SI bandit report from directory
* aggragation needs to contain:
  * bandit version
  * package index
  * package name
  * package version
* have tekton create a container image on quay on tag

**Comment by pacospace** [comment]
This was done by @KPostOffice, it can be closed!
