### ISSUE TITLE
create python script to schedule SI for all i_p_v

### ISSUE THREAD

**Issue by goern** [thoth-station/si-aggregator#2]

**Comment by goern** [comment]
@KPostOffice is this something we still need/want?

**Comment by goern** [comment]
@KPostOffice ping

**Comment by KPostOffice** [comment]
Heya, sorry I missed this one. I know that doing this would be pretty resource intensive. I think the main question is, "what value will it provide?" Can we attract more people by adding more performance and build info? or is there a good chunk of people looking for `security` advises from thoth?

In short :shrug:
